export const ADD_VALUE_USERS = "ADD_VALUE_USERS";
export const SUBMIT_REGISTRATION = "SUBMIT_REGISTRATION";
export const SUBMIT_AUTH = "SUBMIT_AUTH";
export const ON_REGISTRATION = "ON_REGISTRATION";
export const EXIT_AUTH = "EXIT_AUTH";
